services:

  frontend:
    build: ./frontend
    container_name: frontend_container
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "4321:4321"
    environment:
      - HOST=0.0.0.0