"""Add is_active  to switch

Revision ID: 1638909a020e
Revises: 178558d1fcba
Create Date: 2025-01-21 17:56:33.290260

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1638909a020e"
down_revision: Union[str, None] = "178558d1fcba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("switches", sa.Column("is_active", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("switches", "is_active")
    # ### end Alembic commands ###
