"""Add expiration_datetime to switch

Revision ID: 178558d1fcba
Revises: 434130684bf3
Create Date: 2025-01-21 17:43:25.465502

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "178558d1fcba"
down_revision: Union[str, None] = "434130684bf3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "switches", sa.Column("expiration_datetime", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("switches", "expiration_datetime")
    # ### end Alembic commands ###
