# Defines the name of the workflow as it will appear in GitHub Actions tab
name: Lint

# Specifies when this workflow should run
on:
  push:
    branches: [ main ]  # Runs when code is pushed to main branch
  pull_request:
    branches: [ main ]  # Runs when a PR is created/updated targeting main

jobs:
  lint:
    runs-on: ubuntu-latest    # Uses Ubuntu as the operating system
    steps:
    # Step 1: Checkout the repository code
    - uses: actions/checkout@v4
    
    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    # Step 3: Install Ruff and other dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff
    
    # Step 4: Run the actual linting checks
    - name: Run Ruff
      run: |
        ruff check .        # Checks for code quality issues
        ruff format --check .  # Verifies code formatting 